version: '3.5'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  frontend:
    build: ./example-frontend
    image: exfront
    ports:
      - 5000:5000
  backend:
    build: ./example-backend
    image: exback
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379