version: '3.5'

services:
  nginx:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  psql:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres987
    container_name: db_pgsql
    volumes:
     - database:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
  frontend:
    build: ./example-frontend
    image: exfront
    ports:
      - 5000:5000
  backend:
    build: ./example-backend
    image: exback
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db_pgsql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres987
  
volumes:
  database: